/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabajo4_ep418;

/**
 *
 * @author MacBook
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreEquipo = new javax.swing.JLabel();
        lblUniversidad = new javax.swing.JLabel();
        lblLenguajeProgramacion = new javax.swing.JLabel();
        lblDatosDeEquipo = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblApellidos1 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        txtEquipo = new javax.swing.JTextField();
        txtUniversidad = new javax.swing.JTextField();
        txtLenguajeProgramacion = new javax.swing.JTextField();
        txtNombre1 = new javax.swing.JTextField();
        txtApellidos1 = new javax.swing.JTextField();
        lblNombre2 = new javax.swing.JLabel();
        lblApellidos2 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JTextField();
        txtApellidos2 = new javax.swing.JTextField();
        lblNombre3 = new javax.swing.JLabel();
        txtApellidos3 = new javax.swing.JTextField();
        lblApellidos3 = new javax.swing.JLabel();
        txtNombre3 = new javax.swing.JTextField();
        lblConfirmacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario");

        lblNombreEquipo.setText("Nombre del equipo:");

        lblUniversidad.setText("Universidad:");

        lblLenguajeProgramacion.setText("Lenguaje de programación:");

        lblDatosDeEquipo.setText("Datos de los integrantes del equipo");

        lblNombre1.setText("Nombre del integrante:");

        lblApellidos1.setText("Apellidos del integrante:");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        lblNombre2.setText("Nombre del integrante:");

        lblApellidos2.setText("Apellidos del integrante:");

        txtApellidos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidos2ActionPerformed(evt);
            }
        });

        lblNombre3.setText("Nombre del integrante:");

        lblApellidos3.setText("Apellidos del integrante:");

        lblConfirmacion.setText("    ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(lblDatosDeEquipo)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btnIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBorrar)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblLenguajeProgramacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLenguajeProgramacion, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreEquipo)
                            .addComponent(lblUniversidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEquipo)
                            .addComponent(txtUniversidad, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre1)
                            .addComponent(lblApellidos1)
                            .addComponent(lblNombre2)
                            .addComponent(lblApellidos2)
                            .addComponent(lblNombre3)
                            .addComponent(lblApellidos3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre1)
                            .addComponent(txtApellidos1)
                            .addComponent(txtNombre2)
                            .addComponent(txtApellidos2)
                            .addComponent(txtApellidos3)
                            .addComponent(txtNombre3)))
                    .addComponent(lblConfirmacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEquipo)
                    .addComponent(txtEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUniversidad)
                    .addComponent(txtUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLenguajeProgramacion)
                    .addComponent(txtLenguajeProgramacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblDatosDeEquipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre1)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidos1)
                    .addComponent(txtApellidos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre2)
                    .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidos2)
                    .addComponent(txtApellidos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre3)
                    .addComponent(txtNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidos3)
                    .addComponent(txtApellidos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblConfirmacion)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnBorrar))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidos2ActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        try {
            String nombre= String.valueOf(txtEquipo.getText());
            String universidad = String.valueOf(txtUniversidad.getText());
            String lenguaje = String.valueOf(txtLenguajeProgramacion.getText());
            
            EquipoMaratonProgramacion equipo = new EquipoMaratonProgramacion(nombre, universidad,lenguaje);
            
            String nombreProgramador1;
            String apellidosProgramador1;
            
            String nombreProgramador2;
            String apellidosProgramador2;
            
            String nombreProgramador3;
            String apellidosProgramador3;
            
            nombreProgramador1 = String.valueOf(txtNombre1.getText());
            EquipoMaratonProgramacion.validarCampo(nombreProgramador1);
            apellidosProgramador1 = String.valueOf(txtApellidos1.getText());
            Programador programador1 = new Programador(nombreProgramador1, apellidosProgramador1);
            equipo.añadir(programador1);
            
            nombreProgramador2 = String.valueOf(txtNombre2.getText());
            EquipoMaratonProgramacion.validarCampo(nombreProgramador2);
            apellidosProgramador2 = String.valueOf(txtApellidos2.getText());
            Programador programador2 = new Programador(nombreProgramador2, apellidosProgramador2);
            equipo.añadir(programador2);
            
            nombreProgramador3 = String.valueOf(txtNombre3.getText());
            EquipoMaratonProgramacion.validarCampo(nombreProgramador3);
            apellidosProgramador3 = String.valueOf(txtApellidos3.getText());
            Programador programador3 = new Programador(nombreProgramador3, apellidosProgramador3);
            equipo.añadir(programador3);
            
            lblConfirmacion.setText("Se obtuvieron los datos del equipo.");
            
        } catch (Exception e){
            e.printStackTrace();
            lblConfirmacion.setText("Ocurrio un error revise los datos ingresados");   
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        txtUniversidad.setText("");
        txtEquipo.setText("");
        txtLenguajeProgramacion.setText("");
        
        txtNombre1.setText("");
        txtApellidos1.setText("");
        
        txtNombre2.setText("");
        txtApellidos2.setText("");
        
        txtNombre3.setText("");
        txtApellidos3.setText("");
        
        lblConfirmacion.setText("");
    }//GEN-LAST:event_btnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel lblApellidos1;
    private javax.swing.JLabel lblApellidos2;
    private javax.swing.JLabel lblApellidos3;
    private javax.swing.JLabel lblConfirmacion;
    private javax.swing.JLabel lblDatosDeEquipo;
    private javax.swing.JLabel lblLenguajeProgramacion;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblNombreEquipo;
    private javax.swing.JLabel lblUniversidad;
    private javax.swing.JTextField txtApellidos1;
    private javax.swing.JTextField txtApellidos2;
    private javax.swing.JTextField txtApellidos3;
    private javax.swing.JTextField txtEquipo;
    private javax.swing.JTextField txtLenguajeProgramacion;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtNombre3;
    private javax.swing.JTextField txtUniversidad;
    // End of variables declaration//GEN-END:variables
}
